load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "grype_updater",
    srcs = ["main.go"],
    importpath = "github.com/hxtk/rules_anchore/tools/grype_updater",
    visibility = ["//visibility:public"],
)
