# It is actually necessary to declare this first because we have added io_bazel_rules_go
# as an optional dependency. Normally, it is configured by calling `extra_deps()`, but
# users coming from 2.0.0 wouldn't have that call in their WORKSPACE.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "59536e6ae64359b716ba9c46c39183403b01eabfbd57578e84398b4829ca499a",
    strip_prefix = "rules_docker-0.22.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.22.0/rules_docker-v0.22.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

# Instantiate test workspace
local_repository(
    name = "com_github_hxtk_rules_anchore",
    path = "../../../",
)

# Can we load dependencies the same way we did in 2.0.0?
# extra_deps was absent then, so we should be able to omit it
# and expect all 2.0.0 features to continue working.
load("@com_github_hxtk_rules_anchore//:deps.bzl", "anchore_deps")

anchore_deps()

# Test dependencies
load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
    name = "distroless_base",
    digest = "sha256:02f4c952f790848aa6ffee8d241c67e0ac5364931c76a80094348af386076ad4",
    registry = "gcr.io",
    repository = "distroless/base-debian11",
    tag = "nonroot",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
http_file(
    name = "cve_database",
    sha256 = "9721e633543bb663814fad30a6f84f8f5de2fedcaaaea42547490ffb18e1f360",
    urls = ["https://toolbox-data.anchore.io/grype/databases/vulnerability-db_v3_2021-06-01T20:56:41Z.tar.gz"],
)
